### ISSUE TITLE
can not detect rust file type.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/dein.vim#110]
# Problems summary
can not detect rust filetype when open *.rs file. but `:e *.rs` works well.

## Expected
`vim src/main.rs` should auto detect rust filetype.

## Environment Information
 * OS:arch
 * Vim version:neovim_HEAD

## Provide a minimal .vimrc with less than 50 lines (Required!)
test/testrust.vim
```vim
if &compatible
    set nocompatible
endif
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/vimfiles'))
call dein#add('racer-rust/vim-racer',          {'on_ft' : 'rust'})
let g:racer_cmd = $HOME."/.cargo/bin/racer"
call dein#add('wsdjeg/rust.vim')

call dein#end()

filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

 1. vim -u test/testrust.vim  ~/sources/guessing_game/src/main.rs
 2. `:set ft?`
 3. `:e ~/sources/guessing_game/src/main.rs`
 4. `:set ft?`

**Comment by wsdjeg** [comment]
@Shougo  not only file type detect not works well, but https://github.com/Yggdroot/indentLine  
this plugin also not works well, you can not see indent line when use `vim Foo.java`, but `:e Foo.java`again, you will see the indent line.

**Comment by Shougo** [comment]
Fixed both problems.

**Comment by wsdjeg** [comment]
Thanks, now it works well, both filedetect and indentline.

**Comment by mqudsi** [comment]
This seems to be broken again in the latest dein against the official rust.vim fork from https://github.com/rust-lang/rust.vim

**Comment by Shougo** [comment]
@mqudsi OK.  I will test it.
Please upload the minimal vimrc and the reproduce ways from Vim starting.

**Comment by mqudsi** [comment]
@Shougo I was originally running a commit that pre-date #110, but after upgrading I was still having this problem (when I posted). However, it seems that something must have been cached because it is now working. So #110 fixed this.

**Comment by Shougo** [comment]
OK
