### ISSUE TITLE
Setting {'merged': 0} for all plugins makes help files unaccessible after recaching runtimepath

### ISSUE THREAD

**Issue by leonidborisenko** [Shougo/dein.vim#55]
# Problems summary

When I pass `{'merged': 0}` as a default options for **all** plugins, every call of `dein#update()` makes help files unaccessible (with `E149: Sorry, no help for <...>` reaction to `:help <...>` command)

I failed in making simple reproducible example of my described case, but this behavior can be also reproduced by initial installing of plugins with `{'merged': 0}`.

My temporary fix is to comment [this line](https://github.com/Shougo/dein.vim/blob/fd1bdcb3888d6a034b03b711fd7d42555305de8f/autoload/dein/install.vim#L207l) in `autoload/dein/install.vim` before every `dein#update()`/`dein#recache_runtimepath()`.

## Expected

`:help` works for all help files provided by plugins 

## Environment Information
 * OS: Linux
 * Vim version:
```
NVIM v0.1.3-317-gbd81239
Build type: Release
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Directory where this minimal vimrc file is located.
let s:rcdir = expand('<sfile>:p:h')
" Base path of dein.vim.
let s:dein_base_path = s:rcdir.'/dein'
" Path to cloned repository of dein.vim.
let s:dein_clone_path = s:rcdir.'/dein/dein.vim'

if has('vim_starting')
  if &compatible | set nocompatible | endif
  let &runtimepath .= ','.s:dein_clone_path
endif

call dein#begin(s:dein_base_path)
call dein#add('thinca/vim-prettyprint', {'merged': 0})
call dein#end()

filetype plugin indent on
syntax on
```

## The reproduce ways from Vim starting (Required!)

 1. `:call dein#install()`
 2. `:help prettyprint`

## Screen shot (if possible)

![a](https://cloud.githubusercontent.com/assets/509638/14042969/2a995c34-f290-11e5-8f42-6f606e373553.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by leonidborisenko** [comment]
Thanks. But I stiil can reproduce a bug even with the version containing fix commit.

First of all, I beleive the fix should contain copying files from non-merged plugins, not copying files from merged plugins. I left comment on relevant line in commit diff.

But *when I make a change in my local dein.vim clone* as it's said in commit comment, bug still is reproduced. Though copying is done, when I look in `dein/.dein/doc`, it's a helpfile from `vim-prettyprint` plugin, not a directory containg the helpfile.

```shell
$ tree -p --du -F dein/.dein
dein/.dein
├── [drwxr-xr-x         224]  after/
│   └── [drwxr-xr-x         152]  ftdetect/
│       └── [drwxr-xr-x          80]  after/
│           └── [-rw-r--r--           0]  ftdetect.vim
├── [-rw-r--r--        6498]  doc
└── [drwxr-xr-x          80]  ftdetect/
    └── [-rw-r--r--           0]  ftdetect.vim
```

```shell
$ head dein/.dein/doc
*prettyprint.txt*       Prettyprint vim variables.

Version: 0.3.4
Author : thinca <thinca+vim@gmail.com>
License: zlib License

==============================================================================
CONTENTS                                        *prettyprint-contents*

INTRODUCTION                    |prettyprint-introduction|

```

And here is `:messages` output after `:call dein#install()`:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
[dein] Updated plugins:
[dein]   vim-prettyprint
[dein]     https://github.com/thinca/vim-prettyprint/compare/...c49f3ccfe7d8d475b2d0bc06d44684b15ba0f692
[dein] Error generating helptags:
[dein] Vim(call):E739: Cannot create directory /tmp/db/dein/.dein/doc: file already exists
[dein] function <SNR>29_job_handler_neovim[1]..<SNR>29_job_handler[15]..<SNR>29_install_async[13]..dein#install#_recache_runtimepath[14]..<SNR>29_helptags[4]..dein#util#_get_tags_path, line 7
remote/host: generated the manifest file in "./.-rplugin~"
[dein] Runtimepath updated: (2016/03/26 09:44:54)

```

**Comment by Shougo** [comment]
@leonidborisenko Fixed.  Please update.

**Comment by leonidborisenko** [comment]
With the last version, bug is fixed. Helpfiles are (still) accessible after `dein#install()` and `dein#update()`. Thanks.
